name: Keep Render Service Awake

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SERVICE_URL: ${{ secrets.RENDER_SERVICE_URL }}
    steps:
      - name: Ping Render Service
        run: |
          curl -s ${SERVICE_URL}/ping > /dev/null
          echo "Pinged service at $(date)"
